apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fathom
  labels:
    app: fathom
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: fathom
    app.kubernetes.io/instance: {{ .Release.Name }}
