(()=>{'use strict';
 const $=id=>document.getElementById(id), state={workspace:'',models:[],data:null,task:null,busy:false};
 const node=(tag,text,cls)=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e};

 function markdown(target,text){
  const inline=(el,value)=>{const re=/(\*\*[^*]+\*\*|`[^`]+`)/g;let cursor=0;for(const match of value.matchAll(re)){el.append(document.createTextNode(value.slice(cursor,match.index)));el.append(node(match[0].startsWith('**')?'strong':'code',match[0].startsWith('**')?match[0].slice(2,-2):match[0].slice(1,-1)));cursor=match.index+match[0].length}el.append(document.createTextNode(value.slice(cursor)))};
  target.replaceChildren();const lines=String(text).split('\n');for(let i=0;i<lines.length;i++){const line=lines[i].trim();if(line.startsWith('```')){const code=[];while(++i<lines.length&&!lines[i].trim().startsWith('```'))code.push(lines[i]);const pre=node('pre','');pre.append(node('code',code.join('\n')));target.append(pre);continue}
   if(line.startsWith('|')&&/^\|?[\s:|-]+\|$/.test((lines[i+1]||'').trim())){const table=node('table','');const row=(value,header)=>{const tr=node('tr','');for(const cell of value.trim().replace(/^\||\|$/g,'').split('|')){const td=node(header?'th':'td','');inline(td,cell.trim());tr.append(td)}table.append(tr)};row(line,true);i++;while(i+1<lines.length&&lines[i+1].trim().startsWith('|'))row(lines[++i],false);target.append(table);continue}
   const p=node(/^#{1,3} /.test(line)?'h3':'p','');inline(p,line.replace(/^#{1,3} /,''));target.append(p)
  }
 }
 function headers(){return {Authorization:'Bearer '+(localStorage.getItem('fantazm_device_token')||''),'Content-Type':'application/json'}}
 async function api(path='',body){const r=await fetch('/api/v1/board'+path,{method:body===undefined?'GET':'POST',headers:headers(),body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||`Request failed (${r.status})`);return data}
 const report=e=>{$('status').textContent=e.message;$('task-status').textContent=e.message};
 function options(select,values,empty){select.replaceChildren();if(empty!==undefined){const o=node('option',empty);o.value='';select.append(o)}for(const value of values){const o=node('option',value);o.value=value;select.append(o)}}
 async function init(){const data=await api();state.models=data.models;$('run-setup').textContent=data.runSetup||'Runs use offline containers. You start each builder and reviewer; completion requires human approval.';const current=state.workspace;$('workspace').replaceChildren();for(const w of data.workspaces){const o=node('option',w.name);o.value=w.id;$('workspace').append(o)}state.workspace=data.workspaces.some(w=>w.id===current)?current:(data.workspaces[0]?.id||'');$('workspace').value=state.workspace;await refresh()}
 async function refresh(){if(!state.workspace){$('workspace-content').hidden=true;return}const id=state.workspace;const data=await api('/'+id);if(id!==state.workspace)return;if(state.data&&JSON.stringify(state.data)===JSON.stringify(data))return;state.data=data;$('workspace-content').hidden=false;render();}
 function render(){const data=state.data,write=data.role!=='viewer';$('workspace-id').textContent='Workspace ID: '+state.workspace;$('member-form').hidden=data.role!=='admin';$('task-form').querySelector('button').disabled=!write;
  $('members').replaceChildren(...data.members.map(m=>node('div',m.userId+' · '+m.role,'person')));
  $('board').replaceChildren();for(const key of ['backlog','ready','running','review','blocked','done']){const lane=node('div','','lane');lane.append(node('h2',key[0].toUpperCase()+key.slice(1)));for(const t of data.tasks.filter(t=>t.state===key)){const card=node('button','','task');card.style.width='100%';card.style.textAlign='left';card.append(node('strong',t.title),node('small',t.assignee||'Unassigned'));if(t.source)card.append(node('small',' · '+t.source));card.onclick=()=>openTask(t);lane.append(card)}$('board').append(lane)}
  options($('connection'),data.connections.map(c=>c.provider));$('import-form').hidden=!data.connections.length||!write;$('connections-note').textContent=data.connections.length?data.connections.map(c=>c.provider+' · '+c.scope).join(', '):'No connection configured. The built-in board is ready to use. Your instance administrator can connect this workspace to a Linear team or Jira project.';
  renderActivity($('activity'),data.activity);if(state.task){const latest=data.tasks.find(t=>t.id===state.task.id);if(latest&&latest.revision!==state.task.revision&&!state.busy){if(state.task.state==='running'){openTask(latest);return}$('task-status').textContent='This task changed. Close and reopen it before editing.'}}
 }
 function renderActivity(target,events){target.replaceChildren(...events.map(e=>{const row=node('div','','activity');row.append(node('small',new Date(e.at).toLocaleString()+' · '+e.actor+' · '+e.kind),node('pre',e.text));return row}))}
 function openTask(t){state.task=t;$('task-status').textContent='';$('edit-title').value=t.title;$('edit-description').value=t.description;options($('edit-assignee'),state.data.members.map(m=>m.userId),'Unassigned');$('edit-assignee').value=t.assignee;for(const field of ['builder','reviewer']){options($('edit-'+field),state.models,'Default model');$('edit-'+field).value=t[field]}
  $('task-state').textContent='State: '+t.state+' · revision '+t.revision;markdown($('handoff'),t.handoff||'No builder handoff yet.');markdown($('review'),t.review||'No review yet.');$('publish-preview').hidden=true;$('task-comment').value='';const link=$('external-link');link.hidden=true;try{const url=new URL(t.externalUrl);if(url.protocol==='https:'){link.href=url.href;link.hidden=false}}catch{};$('publish').hidden=!t.source||!t.handoff;renderActivity($('task-activity'),state.data.activity.filter(e=>e.taskId===t.id));
  const readOnly=state.data.role==='viewer';for(const el of $('task-dialog').querySelectorAll('input,textarea,select,button[data-action]'))el.disabled=readOnly||t.state==='running';$('edit-form').querySelector('button').disabled=readOnly||t.state==='running';for(const el of $('task-dialog').querySelectorAll('[data-action="cancel"]'))el.disabled=readOnly||t.state!=='running';$('task-dialog').querySelector('[data-action="approve"]').disabled=readOnly||t.state!=='review'||!t.review;if(!$('task-dialog').open)$('task-dialog').showModal();
 }
 async function action(name,extra={}){if(state.busy||!state.task)return;state.busy=true;try{const t=await api(`/${state.workspace}/tasks/${state.task.id}/${name}`,{revision:state.task.revision,text:$('task-comment').value,...extra});await refresh();if(t.id)openTask(t);else $('task-status').textContent=t.status||'Saved.'}catch(e){report(e)}finally{state.busy=false}}
 $('workspace-form').onsubmit=async e=>{e.preventDefault();try{const w=await api('',{name:$('workspace-name').value});state.workspace=w.id;$('workspace-name').value='';await init()}catch(e){report(e)}};
 $('workspace').onchange=()=>{state.task=null;$('task-dialog').close();state.workspace=$('workspace').value;state.data=null;refresh().catch(report)};
 $('task-form').onsubmit=async e=>{e.preventDefault();try{const t=await api('/'+state.workspace+'/tasks',{title:$('task-title').value,description:$('task-description').value});$('task-form').reset();await refresh();openTask(t)}catch(e){report(e)}};
 $('member-form').onsubmit=async e=>{e.preventDefault();try{await api('/'+state.workspace+'/members',{userId:$('member-id').value,role:$('member-role').value});await init()}catch(e){report(e)}};
 $('import-form').onsubmit=async e=>{e.preventDefault();try{const t=await api('/'+state.workspace+'/import',{provider:$('connection').value,id:$('issue-key').value});await refresh();openTask(t)}catch(e){report(e)}};
 $('edit-form').onsubmit=e=>{e.preventDefault();action('edit',{title:$('edit-title').value,description:$('edit-description').value,assignee:$('edit-assignee').value,builder:$('edit-builder').value,reviewer:$('edit-reviewer').value})};
 for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>action(b.dataset.action);
 $('publish').onclick=()=>{$('publish-text').textContent='Fathom team handoff — '+state.task.title+'\nState: '+state.task.state+'\n\n'+state.task.handoff+'\n\nReview:\n'+state.task.review;$('publish-preview').hidden=false};
 $('close-dialog').onclick=()=>{$('task-dialog').close();state.task=null};$('task-dialog').onclose=()=>{state.task=null};
 $('download').onclick=async()=>{try{const r=await fetch('/api/v1/board/'+state.workspace+'/archive',{headers:headers()});if(!r.ok)throw Error('Workspace archive unavailable');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='workspace.tar.gz';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){report(e)}};
 init().catch(report);setInterval(()=>{if(!document.hidden&&!state.busy)refresh().catch(report)},4000);
})();
